### ISSUE TITLE
Cli / dashboard 

### ISSUE THREAD

**Issue by gedw99** [bruth/nats-by-example#1]
Thanks for putting the work into building this .

Do you think a golang cli or even a dashboard is useful to yourself or other nats users ? I ask because I was thinking about building one for the last few months . 

Also it might be possible to build the tool on top of the nats cli to get insight into the cluster and so feedback changes happening up to the high level too. 

The higher level tool could eventually incorporate HCL / terraform to make things cloud agnostic but i suspect there might already be code doing this in the main nats org on GitHub .

**Comment by bruth** [comment]
@gedw99 I think the basic server monitoring features of the nats cli (with the `watch` command) are generally fine for small operational changes, when they need to be performed. So I have not have not personally felt the need to put effort into creating one.. although I think if one existed, it would be convenient. However for teams of people who needs to work with nats and are not as intimate with the intricacies, I could see value in a more accessible dashboard.

Tangential, but related to this repo, nats-server v2.8+ has beta support for live migrations of streams/consumers.

**Comment by gedw99** [comment]
@bruth good points about gui. I will try to start with one, but don't have time right now.  If you feel like it , could you outline the low hanging fruit for it. I think you know more than me on this.

live migrations of streams/consumers is great. I did not know about it.
